- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  salary: 20000 # Frontier
  setPreference: false
#  overrideConsoleVisibility: true # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # access: # Frontier
  # - Maintenance # Frontier
  # extendedAccess: # Frontier
  # - External # Frontier
